name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Directory Layout
      run: |
        mkdir ./InT
        mkdir ./InT/src
        mkdir ./InT/src/bootstrap
        mv -f ./asm ./InT/src/bootstrap
        mv -f ./cpu ./InT/src/bootstrap
        mv -f ./integration_testing ./InT/src/bootstrap
        mv -f ./defs ./InT/src/bootstrap
        ls -lah ./InT/
        ls -lah ./InT/src
        ls -lah ./InT/src/bootstrap
        
    - name: Regular Tests
      run: |
        export GOPATH=/home/runner/work/bootstrap/bootstrap/InT
        cd ./InT/src/bootstrap/cpu
        ls -lah
        go test -test.v
        

    - name: Integration Tests
      run: |
        export GOPATH=/home/runner/work/bootstrap/bootstrap/InT/
        cd ./InT/src/bootstrap/integration_testing
        ls -lah
        go test -test.v
