name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Directory Layout
      run: |
        mkdir ./InT
        mkdir ./InT/src
        mkdir ./InT/src/bootstrap
        mkdir ./InT/bin
        mv -f ./asm ./InT/src/bootstrap
        mv -f ./cpu ./InT/src/bootstrap
        mv -f ./integration_testing ./InT/src/bootstrap
        mv -f ./defs ./InT/src/bootstrap
        mv -f ./cmd ./InT/src/bootstrap
        mv -f ./emulathor ./InT/src/bootstrap
        mv -f ./sw ./InT
        ls -lah ./InT/
        ls -lah ./InT/src
        ls -lah ./InT/src/bootstrap
        
        
    - name: Check fmt
      run: |
        test -z $(gofmt -l ./InT/src/bootstrap/cpu)
        test -z $(gofmt -l ./InT/src/bootstrap/asm)
        test -z $(gofmt -l ./InT/src/bootstrap/defs)
        test -z $(gofmt -l ./InT/src/bootstrap/integration_testing)
        test -z $(gofmt -l ./InT/src/bootstrap/cmd/basm)
        test -z $(gofmt -l ./InT/src/bootstrap/emulathor)
        
    - name: Regular Tests
      run: |
        export GOPATH=/home/runner/work/bootstrap/bootstrap/InT
        cd ./InT/src/bootstrap/cpu
        ls -lah
        go test -test.v
        

    - name: Integration Tests
      run: |
        export GOPATH=/home/runner/work/bootstrap/bootstrap/InT/
        cd ./InT/src/bootstrap/integration_testing
        ls -lah
        go test -test.v

    - name: Build cmds
      run: |
        export GOPATH=/home/runner/work/bootstrap/bootstrap/InT/
        cd ./InT/src/bootstrap/cmd/basm
        go build
        
    - name: Build emulathor
      run: |
        export GOPATH=/home/runner/work/bootstrap/bootstrap/InT/
        cd ./InT/src/bootstrap/emulathor
        go build
        
    - name: Build sw/asm
      run: |
        ./InT/src/bootstrap/cmd/basm/basm -module=stdlib.M -paths=./InT/sw/asm
        
    - name: Build sw/os
      run: |
        ./InT/src/bootstrap/cmd/basm/basm -module=kernel.M -paths=./InT/sw/os:./InT/sw/asm
        
    - name: Run sw/asm/_tests
      run: |
        ./InT/src/bootstrap/cmd/basm/basm -module=stdlib_test.M -paths=./InT/sw/asm -out=./InT/bin/stdlib_test.bin
        ./InT/src/bootstrap/emulathor/emulathor -bin=./InT/bin/stdlib_test.bin